# Dual Confirmation Trading System Configuration

# CipherB Settings (exact Pine Script parameters)
cipherb:
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60

# StochRSI Settings
stochrsi:
  rsi_period: 14
  stoch_period: 14
  smooth_k: 3
  smooth_d: 3
  oversold: 30
  overbought: 70

# System Settings
system:
  freshness_minutes: 2
  batch_size: 12
  rate_limit_seconds: 0.5

# Exchange Settings
exchanges:
  primary: "BingX"
  fallback: "KuCoin"
  timeout_ms: 30000
  rate_limit_ms: 300

# Alert Settings
alerts:
  enable_telegram: true
  enable_fallback_alerts: true
  show_stochrsi_details: true
