# API Configuration
coingecko:
  base_url: "https://api.coingecko.com/api/v3"
  rate_limit: 1.2  # seconds between requests

bingx:
  base_url: "https://open-api.bingx.com"
  
# Market Filters
filters:
  standard:
    min_market_cap: 500000000   # 500M USD
    min_volume_24h: 30000000    # 30M USD
  high_risk:
    min_market_cap: 10000000    # 10M USD
    max_market_cap: 500000000   # 500M USD
    min_volume_24h: 10000000    # 10M USD

# Alert Configuration
alerts:
  cooldown_hours: 2
  timezone_offset: "+05:30"

# Pagination
scan_pages: 6
coins_per_page: 250
