name: Daily Market Scan
on:
  schedule:
    - cron: '30 0 * * *'  # 06:00 IST = 00:30 UTC
  workflow_dispatch:  # Allow manual trigger
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create cache directory
        run: mkdir -p cache
      - name: Run daily scan
        run: python src/data_fetcher.py --daily-scan
        env:
          PYTHONPATH: ${{ github.workspace }}

