name: Signal Detection
on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:        # Manual trigger
jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run signal detection
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          STANDARD_CHAT_ID: ${{ secrets.STANDARD_CHAT_ID }}
          HIGH_RISK_CHAT_ID: ${{ secrets.HIGH_RISK_CHAT_ID }}
          BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
          BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
        run: python src/main.py
